config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, except: [:destroy] do
    resources :reviews, only: [:new, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: {
    in: ['chinese', 'italian', 'japanese', 'french', 'belgian']
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def show
  end

  def edit
  end
end

private

def set_restaurant
  @restaurant = Restaurant.find(params[:id])
end

def restaurant_params
  params.require(:restaurant).permit(:name, :address, :phone_number, :category)
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end
end

private

def review_params
  params.require(:review).permit(:content, :rating)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <a href="http://localhost:3000/restaurants">
        <img src="https://img.pngio.com/restaurant-cutlery-circular-symbol-of-a-spoon-and-a-fork-in-a-circle-restaurant-png-338_338.jpg" class="brand">
      </a>
      <a href="http://localhost:3000/restaurants/new">
        <img src="https://image.flaticon.com/icons/svg/54/54908.svg" class="add-icon">
      </a>
    </div>

    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">
<h2> Update: <%= @restaurant.name %></h2>

<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: ['chinese', 'italian', 'japanese', 'french', 'belgian']%>
  <%= f.submit "Update", class: "btn btn-primary" %>
<% end %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="restaurants">
    <% @restaurants.each do |restaurant| %>
      <div class="restaurant">
        <h2><%= link_to restaurant.name, restaurant_path(restaurant)%></h2>
      </div>
    <%end%>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
<h2> Create a new Restaurant</h2>

<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: ['chinese', 'italian', 'japanese', 'french', 'belgian']%>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
<h2><%= @restaurant.name %></h2>
<br>

  <div>
    <ul>
      <li><strong>Address:</strong> <%= @restaurant.address %></li>
      <li><strong>Phone Number:</strong> <%= @restaurant.phone_number %></li>
      <li><strong>Category:</strong> <%= @restaurant.category.capitalize %></li>
    </ul>
  </div>


  <div id="back-btn">
    <%= link_to 'Edit', edit_restaurant_path(@restaurant), class: 'btn btn-primary' %>
  </div>
  <div id="back-btn">
    <%= link_to 'Add a Review', new_restaurant_review_path(@restaurant), class: 'btn btn-primary' %>
  </div>
  <ul>
    <br>
    <br>
    <br>
    <% @restaurant.reviews.each do |review| %>
      <p>Review by: Jack Mentali</p>
      <p><%= review.content %> | Rated by user: <%= review.rating %> /5<p>
    <% end %>
  </ul>
</div>

app/views/reviews/new.html.erb
<div class="container">
<h2> Review for <%= @restaurant.name %></h2>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5]%>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>
</div>